#define PLAY_BUTTON 10
#define COLOR_BUTTON 8
#define BRIGHTNESS_PIN A1
#define SPEED_PIN A2
#define LED_PIN 2

#define PALETTE_ADDRESS 5
#define DIRECTION_ADDRESS 6

#define NUM_LEDS 43
#define BRIGHTNESS 255
#define LED_TYPE WS2811
#define COLOR_ORDER GRB
#define MAX_BRIGHTNESS 128

#define UPDATES_PER_SECOND 100